name: paperless-ngx
services:
  - name: web
    source_dir: /
    github:
      repo: dineshPULSY/pulsydocs-paperless-ngx
      branch: main
      deploy_on_push: true
    run_command: /init
    environment_slug: docker
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8000
    health_check:
      http_path: /
    envs:
      - key: PAPERLESS_SECRET_KEY
        value: Zaqwsx
        type: SECRET
      - key: PAPERLESS_URL
        value: ${APP_URL}
      - key: PAPERLESS_TIME_ZONE
        value: UTC
      - key: PAPERLESS_OCR_LANGUAGE
        value: eng
      - key: PAPERLESS_ADMIN_USER
        value: admin
      - key: PAPERLESS_ADMIN_PASSWORD
        value: admin
        type: SECRET
      - key: PAPERLESS_ADMIN_MAIL
        value: admin@example.com
      - key: PAPERLESS_REDIS
        value: ${redis.REDIS_URL}
      - key: PAPERLESS_DBHOST
        value: ${db.HOSTNAME}
      - key: PAPERLESS_DBPORT
        value: ${db.PORT}
      - key: PAPERLESS_DBNAME
        value: ${db.DATABASE}
      - key: PAPERLESS_DBUSER
        value: ${db.USERNAME}
      - key: PAPERLESS_DBPASS
        value: ${db.PASSWORD}
      - key: PAPERLESS_DBSSLMODE
        value: require
databases:
  - name: db
    engine: PG
    version: "15"
    size: db-s-dev-database
services:
  - name: redis
    engine: REDIS
    version: "7"
    size: db-s-dev-database
